version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: fyle-app
        ports:
            - 5000:5000
        # volumes:
        #     - ./:/app
